### ISSUE TITLE
Need preprocessor exclusion on windows.h with Unix Makefiles

### ISSUE THREAD

**Issue by drankinatty** [FG-33/TicTacToeML#1]
Tried to build to help with your artifact question on SO and received:

Circle.cpp:1:10: fatal error: windows.h: No such file or directory

which I gather means there needs to be an #if defined (_WIN32) || defined (_WIN64) guard around the inclusion?

**Comment by FG-33** [comment]
Thanks for the suggestion. I did not try to compile the project on anything other than windows 7 so the guards were still missing. Now I fixed it. I did test it on ubuntu.
